openapi: 3.0.0
info:
  title: Python to .Net
  description: Still whitout description.
  version: 0.25.1
servers:
- url: http://www.skycoin.net
  description: Main Skycoin server
- url: http://staging.node.skycoin.net
  description: Internal staging server for developer.
components:
  securitySchemes:
    CsrfTokenAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-CSRF-TOKEN  # name of the header, query parameter or cookie
  schemas:
    genericError:
      description: This is a generic error that should be default response
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
paths:
  /api/wallets:
    post:
      summary: Create wallet method.
      description: Should create a new wallet (address) in the blockchain.

      security:
      - CsrfTokenAuth: []

      responses:
        '200':
          description: Private key, wich will be used to sign transactions by the [POST] /api/sign. Address wich identifies the wallet in the blockchain.
          content:
            application/json:
              schema:
                type: object
                properties:
                  privateKey:
                    type: string
                  publicAddress:
                    type: string
        default:
          $ref : '#/components/schemas/genericError'

# To remember :
#  Every post method should use security schema.
#  Feel free to use and reuse components
#  I will remember other stuffs in the process