openapi: 3.0.0
info:
  title: Python to .Net
  description: Still whitout description.
  version: 0.25.1
servers:
- url: http://www.skycoin.net
  description: Main Skycoin server
- url: http://staging.node.skycoin.net
  description: Internal staging server for developer.
components:
  securitySchemes:
    CsrfTokenAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-CSRF-TOKEN  # name of the header, query parameter or cookie
  schemas:
    genericError:
      description: This is a generic error that should be default response
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
paths:
  /somePath:
    get:
      summary: This is a example of a get method.
      description: Some description, is not optional.
      responses:
        '200':    # status code
          description: A response of arrays
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref : '#/components/schemas/genericError'
    post:
      summary: This is a example of a post method.
      description: Some description, is not optional.

      security:
      - CsrfTokenAuth: []

      responses:
        '200':    # status code
          description: A response of arrays
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref : '#/components/schemas/genericError'

# To remember :
#  Every post method should use security schema.
#  Feel free to use and reuse components
#  I think, at some point, someone should use oneOf and anyOf, pls take a look
