openapi: 3.0.0
info:
  title: Python to .Net
  description: Still whitout description.
  version: 0.25.1
servers:
- url: http://www.skycoin.net
  description: Main Skycoin server
- url: http://staging.node.skycoin.net
  description: Internal staging server for developer.
components:
  securitySchemes:
    CsrfTokenAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-CSRF-TOKEN  # name of the header, query parameter or cookie
  schemas:
    genericError:
      description: This is a generic error that should be default response
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
paths:
  /api/IsAlive:
    get:
      summary:  Return some general service info
      description: Check if the server is running correctly
      responses:
        '200':    #status code
          description:  A JSON object containing information about the service
          content:
            application/json:
              schema:
                type: object
                
                properties:
                  name:
                    type: string
                  version:
                    type: string
                  env:
                    type: string
                  isDebug:
                    type: boolean
        
        default:
         $ref: '#/components/schemas/genericError'
                  
                
                  
        
        
    
# To remember :
#  Every post method should use security schema.
#  Feel free to use and reuse components
#  I will remember other stuffs in the process